name: Run tests for MinimalModbus

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10.0-rc.1']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial flake8 mypy pydocstyle coverage coverage[toml]
    - name: Test with unittest
      run: |
        python tests/test_minimalmodbus.py
    - name: Run mypy
      run: |
        mypy minimalmodbus.py tests/ --strict
    - name: Run pydocstyle
      run: |
        pydocstyle minimalmodbus.py
    - name: Run flake8
      run: |
        flake8 minimalmodbus.py
    - name: Generate coverage reports
      run: |
        coverage run tests/test_minimalmodbus.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
